### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sisisin** [sisisin/esbuild-plugin-filename#1]
- [ ] support typescript(with declaration file)
- [ ] support mjs
- [ ] support parser config
- [ ] support bundled script's `__dirname` , `__filename`
- [ ] README
